version: '3'

networks:
# BGP Routing network for location Default
  net-frr-r01:
    ipam:
      config:
        - subnet: 10.225.0.0/24
  net-frr-r02:
    ipam:
      config:
        - subnet: 10.226.0.0/24
  net-frr-r03:
    ipam:
      config:
        - subnet: 10.227.0.0/24  
  net-frr-r04:
    ipam:
      config:
        - subnet: 10.228.0.0/24
# Inter connect netwotk
  net-frr-r01-r02:
    ipam:
      config:
        - subnet: 10.0.255.0/30
  net-frr-r01-r03:
    ipam:
      config:
        - subnet: 10.0.255.4/30
  net-frr-r02-r03:
    ipam:
      config:
        - subnet: 10.0.253.0/30
  net-frr-r02-r04:
    ipam:
      config:
        - subnet: 10.0.254.0/30
  net-frr-r03-r04:
    ipam:
      config:
        - subnet: 10.0.254.4/30
# Mgmt network
  net-mgmt:
    ipam:
      config:
        - subnet: 192.168.10.0/24
volumes:
  data-postgres: {}
  data-opennms: {}

services:
  horizon:
    image: opennms/horizon:29.0.6
    container_name: horizon
    environment:
      - TZ=Europe/London
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OPENNMS_DBNAME=opennms
      - OPENNMS_DBUSER=opennms
      - OPENNMS_DBPASS=opennms
      - JAVA_OPTS=-Xmx4096m -XX:MaxMetaspaceSize=2048m
    networks:
      net-mgmt:
        ipv4_address: 192.168.10.4
    volumes:
      - ./horizon-overlay:/opt/opennms-overlay
    command: ["-s"]
    ports:
      - "8980:8980"
      - "8101:8101"
      - "61616:61616/tcp"
      - "11019:11019/tcp"
    restart: unless-stopped

  database:
    image: postgres:12
    container_name: database
    environment:
      - TZ=Europe/London
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data:delegated
    networks:
      net-mgmt:
        ipv4_address: 192.168.10.3
    restart: unless-stopped

  frr-r01:
    image: frrouting/frr:latest
    container_name: frr-r01
    hostname: frr-r01
    volumes:
      - ./configs/r01/daemons:/etc/frr/daemons
      - ./configs/r01/frr.conf:/etc/frr/frr.conf
      - ./configs/r01/frr.conf:/etc/frr/frr.conf.sav
    networks:
      net-frr-r01:
        ipv4_address: 10.225.0.1
      net-frr-r01-r02:
        ipv4_address: 10.0.255.1
      net-frr-r01-r03:
        ipv4_address: 10.0.255.5
      net-mgmt:
        ipv4_address: 192.168.10.101
    cap_add:
      - cap_sys_admin
      - cap_net_admin
    restart: unless-stopped

  frr-r02:
    image: frrouting/frr:latest
    container_name: frr-r02
    hostname: frr-r02
    volumes:
      - ./configs/r02/daemons:/etc/frr/daemons
      - ./configs/r02/frr.conf:/etc/frr/frr.conf
      - ./configs/r02/frr.conf:/etc/frr/frr.conf.sav
    networks:
      net-frr-r02:
        ipv4_address: 10.226.0.1
      net-frr-r01-r02:
        ipv4_address: 10.0.255.2
      net-frr-r02-r03:
        ipv4_address: 10.0.253.1
      net-frr-r02-r04:
        ipv4_address: 10.0.254.2
      net-mgmt:
        ipv4_address: 192.168.10.102
    cap_add:
      - cap_sys_admin
      - cap_net_admin
    restart: unless-stopped

  frr-r03:
    image: frrouting/frr:latest
    container_name: frr-r03
    hostname: frr-r03
    volumes:
      - ./configs/r03/daemons:/etc/frr/daemons
      - ./configs/r03/frr.conf:/etc/frr/frr.conf
      - ./configs/r03/frr.conf:/etc/frr/frr.conf.sav
    networks:
      net-frr-r03:
        ipv4_address: 10.227.0.1
      net-frr-r01-r03:
        ipv4_address: 10.0.255.6
      net-frr-r02-r03:
        ipv4_address: 10.0.253.2
      net-frr-r03-r04:
        ipv4_address: 10.0.254.5
      net-mgmt:
        ipv4_address: 192.168.10.103
    cap_add:
      - cap_sys_admin
      - cap_net_admin
    restart: unless-stopped

  frr-r04:
    image: frrouting/frr:latest
    container_name: frr-r04
    hostname: frr-r04
    volumes:
      - ./configs/r04/daemons:/etc/frr/daemons
      - ./configs/r04/frr.conf:/etc/frr/frr.conf
      - ./configs/r04/frr.conf:/etc/frr/frr.conf.sav
    networks:
      net-frr-r04:
        ipv4_address: 10.228.0.1
      net-frr-r02-r04:
        ipv4_address: 10.0.254.1
      net-frr-r03-r04:
        ipv4_address: 10.0.254.6
      net-mgmt:
        ipv4_address: 192.168.10.104
    cap_add:
      - cap_sys_admin
      - cap_net_admin
    restart: unless-stopped

# For troubleshoting

  wireshark:
    image: linuxserver/wireshark
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 3000:3000 #optional
    networks:
      net-frr-r02:
      net-mgmt:
        ipv4_address: 192.168.10.5
    volumes:
      - /path/to/config:/config
    restart: unless-stopped
