version: '3'

networks:
# BGP Routing network for location Default
  net-frr-r01:
    ipam:
      config:
        - subnet: 192.168.155.0/24
  net-frr-r02:
    ipam:
      config:
        - subnet: 192.168.156.0/24
  net-frr-peer:
    ipam:
      config:
        - subnet: 10.0.155.0/24
  net-mgmt:
    ipam:
      config:
        - subnet: 192.168.10.0/24
volumes:
  data-postgres: {}
  data-opennms: {}

services:
  horizon:
    image: opennms/horizon:29.0.6
    container_name: horizon
    environment:
      - TZ=Europe/London
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - OPENNMS_DBNAME=opennms
      - OPENNMS_DBUSER=opennms
      - OPENNMS_DBPASS=opennms
      - JAVA_OPTS=-Xmx4096m -XX:MaxMetaspaceSize=2048m
      - OPENNMS_TRAPD_ADDRESS=*
      - OPENNMS_TRAPD_PORT=1162
    networks:
      net-mgmt:
        ipv4_address: 192.168.10.4
    volumes:
      - ./horizon-overlay:/opt/opennms-overlay
    command: ["-s"]
    ports:
      - "8980:8980"
      - "8101:8101"
      - "162:1162/udp"
      - "61616:61616/tcp"
      - "11019:11019/tcp"
    restart: unless-stopped

  database:
    image: postgres:12
    container_name: database
    environment:
      - TZ=Europe/London
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data:delegated
    networks:
      net-mgmt:
        ipv4_address: 192.168.10.3
    restart: unless-stopped

  frr-r01:
    image: frrouting/frr:v8.1.0
    container_name: frr-r01
    hostname: frr-r01
    volumes:
      - ./configs/r01/:/etc/frr/
      # - ./configs/r01/daemons:/etc/frr/daemons
      # - ./configs/r01/frr.conf:/etc/frr/frr.conf
      # - ./configs/r01/frr.conf.sav:/etc/frr/frr.conf.sav
    networks:
      net-frr-r01:
        ipv4_address: 192.168.155.150
      net-frr-peer:
        ipv4_address: 10.0.155.150
      net-mgmt:
        ipv4_address: 192.168.10.101
    cap_add:
      - cap_sys_admin
      - cap_net_admin
    restart: unless-stopped

  frr-r02:
    image: frrouting/frr:v8.1.0
    container_name: frr-r02
    hostname: frr-r02
    volumes:
      - ./configs/r02/:/etc/frr/
      # - ./configs/r02/daemons:/etc/frr/daemons
      # - ./configs/r02/frr.conf:/etc/frr/frr.conf
      # - ./configs/r02/frr.conf.sav:/etc/frr/frr.conf.sav
    networks:
      net-frr-r02:
        ipv4_address: 192.168.156.151
      net-frr-peer:
        ipv4_address: 10.0.155.151
      net-mgmt:
        ipv4_address: 192.168.10.103
    cap_add:
      - cap_sys_admin
      - cap_net_admin
    restart: unless-stopped

# For troubleshoting

  wireshark:
    image: linuxserver/wireshark:3.4.9
    container_name: wireshark
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 3000:3000 #optional
    networks:
      net-frr-r02:
      net-mgmt:
        ipv4_address: 192.168.10.5
    volumes:
      - /path/to/config:/config
    restart: unless-stopped
